// User
export const LOGIN = 'LOGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const GET_TOKEN = 'GET_TOKEN';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';

export const GET_USER_BOARDS_POSTS = 'GET_USER_BOARDS_POSTS';
export const GET_USER_BOARDS_POSTS_SUCCESS = 'GET_USER_BOARDS_POSTS_SUCCESS';
export const GET_USER_BOARDS_POSTS_ERROR = 'GET_USER_BOARDS_POSTS_ERROR';

// Post
export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';
